openapi: 3.0.0
info:
  description: |
    Coinbase provides a simple and powerful REST API to integrate bitcoin, bitcoin cash, litecoin and ethereum payments into your business or application.

    This API reference provides information on available endpoints and how to interact with it. To read more about the API, visit our API documentation.
  title: CoinBase API
  version: 2019-11-15
servers:
- description: Coinbases Production Server
  url: https://api.coinbase.com/v2
paths:
  /user:
    get:
      description: |
        Get current user’s public information. To get user’s email or private information, use permissions wallet:user:email and wallet:user:read. If current request has a wallet:transactions:send scope, then the response will contain a boolean sends_disabled field that indicates if the user’s send functionality has been disabled.
      operationId: CurrentUser
      parameters:
      - description: |
          The user generated message signature (see below)
          The CB-ACCESS-SIGN header is generated by creating a sha256 HMAC using the secret key on the prehash string timestamp + method + requestPath + body (where + represents string concatenation).
        explode: false
        in: header
        name: CB-ACCESS-SIGN
        required: false
        schema:
          default: auto
          type: string
        style: simple
        x-go-default-value: auto
        x-go-default: true
      - description: A timestamp for your request
        explode: false
        in: header
        name: CB-ACCESS-TIMESTAMP
        required: false
        schema:
          type: integer
        style: simple
        x-go-default-value: auto
        x-go-default: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: OK
      security:
      - ApiKeyAuth:
        - wallet:user:read
      summary: Show current user
      tags:
      - users
  /accounts:
    get:
      description: Lists current user’s accounts to which the authentication method
        has access to.
      operationId: ListAccounts
      parameters:
      - description: |
          The user generated message signature (see below)
          The CB-ACCESS-SIGN header is generated by creating a sha256 HMAC using the secret key on the prehash string timestamp + method + requestPath + body (where + represents string concatenation).
        explode: false
        in: header
        name: CB-ACCESS-SIGN
        required: false
        schema:
          default: auto
          type: string
        style: simple
        x-go-default-value: auto
        x-go-default: true
      - description: A timestamp for your request
        explode: false
        in: header
        name: CB-ACCESS-TIMESTAMP
        required: false
        schema:
          type: integer
        style: simple
        x-go-default-value: auto
        x-go-default: true
      - explode: true
        in: query
        name: ending_before
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: starting_after
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 25
          maximum: 100
          minimum: 0
          type: integer
        style: form
      - explode: true
        in: query
        name: order
        required: false
        schema:
          default: desc
          enum:
          - desc
          - asc
          type: string
        style: form
      - explode: true
        in: query
        name: previous_uri
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: next_uri
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: OK
      security:
      - ApiKeyAuth:
        - wallet:accounts:read
      summary: List Accounts
      tags:
      - accounts
  /accounts/{account_id}:
    get:
      description: Show current user’s account. To access the primary account for
        a given currency, a currency string (BTC or ETH) can be used instead of the
        account id in the URL.
      operationId: GetAccount
      parameters:
      - description: |
          The user generated message signature (see below)
          The CB-ACCESS-SIGN header is generated by creating a sha256 HMAC using the secret key on the prehash string timestamp + method + requestPath + body (where + represents string concatenation).
        explode: false
        in: header
        name: CB-ACCESS-SIGN
        required: false
        schema:
          default: auto
          type: string
        style: simple
        x-go-default-value: auto
        x-go-default: true
      - description: A timestamp for your request
        explode: false
        in: header
        name: CB-ACCESS-TIMESTAMP
        required: false
        schema:
          type: integer
        style: simple
        x-go-default-value: auto
        x-go-default: true
      - description: The id of the account
        explode: false
        in: path
        name: account_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: invalid token being used
      security:
      - ApiKeyAuth:
        - wallet:accounts:read
      summary: Retrieve Account
      tags:
      - accounts
  /exchange-rates:
    get:
      description: |
        Get current exchange rates. Default base currency is USD but it can be defined as any supported currency. Returned rates will define the exchange rate for one unit of the base currency.
      operationId: GetExchangeRateFor
      parameters:
      - description: |
          Base currency (default: USD)
        explode: true
        in: query
        name: currency
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: OK
      summary: Get current exchange rates. Default base currency is USD but it can
        be defined as any supported currency. Returned rates will define the exchange
        rate for one unit of the base currency.
      tags:
      - ExchangeRates
  /prices/{currency_pair_1}-{currency_pair_2}/sell:
    get:
      description: |
        Get the total price to buy one bitcoin or ether.

        Note that exchange rates fluctuates so the price is only correct for seconds at the time. This buy price includes standard Coinbase fee (1%) but excludes any other fees including bank fees. If you need more accurate price estimate for a specific payment method or amount, see buy bitcoin endpoint and quote: true option.
      operationId: GetSellPrice
      parameters:
      - description: |
          currency 1
        explode: false
        in: path
        name: currency_pair_1
        required: true
        schema:
          type: string
        style: simple
      - description: |
          currency 2
        explode: false
        in: path
        name: currency_pair_2
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
          description: OK
      summary: Exchanges Rates for currency pair
      tags:
      - ExchangeRates
components:
  parameters:
    CB-ACCESS-SIGN:
      description: |
        The user generated message signature (see below)
        The CB-ACCESS-SIGN header is generated by creating a sha256 HMAC using the secret key on the prehash string timestamp + method + requestPath + body (where + represents string concatenation).
      explode: false
      in: header
      name: CB-ACCESS-SIGN
      required: false
      schema:
        default: auto
        type: string
      style: simple
      x-go-default-value: auto
      x-go-default: true
    CB-ACCESS-TIMESTAMP:
      description: A timestamp for your request
      explode: false
      in: header
      name: CB-ACCESS-TIMESTAMP
      required: false
      schema:
        type: integer
      style: simple
      x-go-default-value: auto
      x-go-default: true
  responses:
    RateLimiting:
      description: being rate limited
    ErrorMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
      description: invalid token being used
  schemas:
    pagination:
      example:
        ending_before: ending_before
        limit: 8.008281904610115
        previous_uri: previous_uri
        next_starting_after: next_starting_after
        starting_after: starting_after
        next_uri: next_uri
        next_ending_before: next_ending_before
        order: desc
      properties:
        ending_before:
          type: string
        starting_after:
          type: string
        next_ending_before:
          type: string
        next_starting_after:
          type: string
        limit:
          default: 25
          maximum: 100
          minimum: 0
          type: number
        order:
          default: desc
          enum:
          - desc
          - asc
          type: string
        previous_uri:
          type: string
        next_uri:
          type: string
      type: object
    Currency:
      example:
        code: code
        color: color
        address_regex: address_regex
        name: name
        sort_index: 6.027456183070403
        asset_id: asset_id
        type: type
        slug: slug
        exponent: 1.4658129805029452
      properties:
        code:
          type: string
        name:
          type: string
        color:
          type: string
        sort_index:
          type: number
        exponent:
          type: number
        type:
          type: string
        address_regex:
          type: string
        asset_id:
          type: string
        slug:
          type: string
      required:
      - asset_id
      - code
      - color
      - exponent
      - name
      - slug
      - sort_index
      - type
      type: object
    Account:
      example:
        allow_deposits: true
        resource: resource
        created_at: 2000-01-23T04:56:07.000+00:00
        type: type
        allow_withdrawals: true
        balance:
          amount: amount
          currency: currency
        updated_at: 2000-01-23T04:56:07.000+00:00
        ready: true
        resource_path: resource_path
        name: name
        currency:
          code: code
          color: color
          address_regex: address_regex
          name: name
          sort_index: 6.027456183070403
          asset_id: asset_id
          type: type
          slug: slug
          exponent: 1.4658129805029452
        id: id
        primary: true
      properties:
        id:
          type: string
        name:
          type: string
        primary:
          type: boolean
        type:
          type: string
        currency:
          $ref: '#/components/schemas/Currency'
        balance:
          $ref: '#/components/schemas/Account_balance'
        created_at:
          format: date-time
          type: string
        updated_at:
          format: date-time
          type: string
        resource:
          type: string
        resource_path:
          type: string
        ready:
          type: boolean
        allow_deposits:
          type: boolean
        allow_withdrawals:
          type: boolean
      required:
      - balance
      - created_at
      - currency
      - id
      - name
      - primary
      - ready
      - resource
      - resource_path
      - type
      - updated_at
      type: object
    ErrorResponse:
      properties:
        errors:
          items:
            $ref: '#/components/schemas/ErrorResponse_errors'
          type: array
      required:
      - errors
      type: object
    User:
      example:
        avatar_url: avatar_url
        profile_url: profile_url
        resource: resource
        profile_location: profile_location
        resource_path: resource_path
        name: name
        id: id
        profile_bio: profile_bio
        username: username
      properties:
        id:
          type: string
        name:
          type: string
        username:
          type: string
        profile_location:
          type: string
        profile_bio:
          type: string
        profile_url:
          type: string
        avatar_url:
          type: string
        resource:
          type: string
        resource_path:
          type: string
      type: object
    CurrencyExchange:
      example:
        amount: amount
        currency: currency
        base: base
      properties:
        amount:
          type: string
        currency:
          type: string
        base:
          type: string
      required:
      - amount
      - base
      - currency
      type: object
    ExchangeRates:
      example:
        rates:
          key: rates
        currency: currency
      properties:
        currency:
          type: string
        rates:
          additionalProperties:
            type: string
          type: object
      required:
      - currency
      - rates
      type: object
    inline_response_200:
      example:
        pagination:
          ending_before: ending_before
          limit: 8.008281904610115
          previous_uri: previous_uri
          next_starting_after: next_starting_after
          starting_after: starting_after
          next_uri: next_uri
          next_ending_before: next_ending_before
          order: desc
        data:
        - allow_deposits: true
          resource: resource
          created_at: 2000-01-23T04:56:07.000+00:00
          type: type
          allow_withdrawals: true
          balance:
            amount: amount
            currency: currency
          updated_at: 2000-01-23T04:56:07.000+00:00
          ready: true
          resource_path: resource_path
          name: name
          currency:
            code: code
            color: color
            address_regex: address_regex
            name: name
            sort_index: 6.027456183070403
            asset_id: asset_id
            type: type
            slug: slug
            exponent: 1.4658129805029452
          id: id
          primary: true
        - allow_deposits: true
          resource: resource
          created_at: 2000-01-23T04:56:07.000+00:00
          type: type
          allow_withdrawals: true
          balance:
            amount: amount
            currency: currency
          updated_at: 2000-01-23T04:56:07.000+00:00
          ready: true
          resource_path: resource_path
          name: name
          currency:
            code: code
            color: color
            address_regex: address_regex
            name: name
            sort_index: 6.027456183070403
            asset_id: asset_id
            type: type
            slug: slug
            exponent: 1.4658129805029452
          id: id
          primary: true
      properties:
        pagination:
          $ref: '#/components/schemas/pagination'
        data:
          items:
            $ref: '#/components/schemas/Account'
          type: array
      required:
      - data
      - pagination
    inline_response_200_1:
      example:
        data:
          rates:
            key: rates
          currency: currency
      properties:
        data:
          $ref: '#/components/schemas/ExchangeRates'
    inline_response_200_2:
      example:
        data:
          amount: amount
          currency: currency
          base: base
      properties:
        data:
          $ref: '#/components/schemas/CurrencyExchange'
    Account_balance:
      example:
        amount: amount
        currency: currency
      properties:
        amount:
          type: string
        currency:
          type: string
      required:
      - amount
      - currency
    ErrorResponse_errors:
      properties:
        id:
          type: string
        message:
          type: string
      required:
      - id
      - message
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: CB-ACCESS-KEY
      type: apiKey
